OPENING_BANNER = "===================================== || VICTIM PROGRAM || ====================================="
MENU_CLOSING_BANNER = ("==================================================================================="
                       "===============")
TRANSFER_KEYLOG_MSG = "GET KEYLOG"
RECEIVED_CONFIRMATION_MSG = "OK"
END_OF_FILE_SIGNAL = b"END_OF_FILE"
RECEIVING_FILE_MSG = "[+] Receiving file: {}"
TRANSFER_SUCCESS_MSG = "[+] FILE TRANSFER SUCCESSFUL: {} has been transferred successfully!"
FILE_CANNOT_OPEN_ERROR = "[+] ERROR: An error has occurred while opening {} : {}"
FILE_CANNOT_OPEN_TO_SENDER = "File has been received, but is either corrupted or not present"
VICTIM_ACK = "ACK"
CLIENT_RESPONSE = "[+] CLIENT SAYS: {}"

START_KEYLOG_MSG = "START"
CHECK_KEYLOG = "CHECK"
STATUS_TRUE = "TRUE"
STATUS_FALSE = "FALSE"
FILE_FOUND_MSG = "[+] The file {} exists in the current directory."
FILE_FOUND_MSG_TO_COMMANDER = "The file {} exists in the current directory."
FILE_NOT_FOUND_ERROR = "[+] ERROR: The file {} does not exist in the current directory."
FILE_NOT_FOUND_TO_CMDR_ERROR = "ERROR: The file {} does not exist in the current directory."
START_KEYLOGGER_PROMPT = "[+] Starting keylogger program..."
RECEIVE_FILE_NAME_PROMPT = "[+] Receiving command to check for file: {} if present..."
DO_CHECK_MSG = "[+] CHECKING FILE EXIST: Now checking if {} exists..."
EXECUTE_KEYLOG_MSG = "[+] Now executing {}..."
EXECUTE_KEYLOG_MSG_TO_CMDR = "Now executing {}..."

FAILED_IMPORT_ERROR = "[+] MISSING DEPENDENCY: Failed to import the following module: {}({})"
FAILED_IMPORT_EXCEPTION_ERROR = "[+] ERROR: An unexpected error occurred while importing {} : {}"
FAILED_IMPORT_MSG = "An unexpected error occurred while importing {} :"
KEYLOG_SUCCESS_MSG_TO_CMDR = "OPERATION SUCCESSFUL: The following file has been created: {}"
KEYLOG_SUCCESS_MSG = "[+] OPERATION SUCCESSFUL: The following file has been created: {}"

