OPENING_BANNER = "===================================== || VICTIM PROGRAM || ====================================="
MENU_CLOSING_BANNER = ("==================================================================================="
                       "===============")
TRANSFER_KEYLOG_MSG = "GET KEYLOG"
RECEIVED_CONFIRMATION_MSG = "OK"
END_OF_FILE_SIGNAL = b"END_OF_FILE"
RECEIVING_FILE_MSG = "[+] Receiving file: {}"
TRANSFER_SUCCESS_MSG = "[+] FILE TRANSFER SUCCESSFUL: {} has been transferred successfully!"
FILE_CANNOT_OPEN_ERROR = "[+] ERROR: An error has occurred while opening {} : {}"
FILE_CANNOT_OPEN_TO_SENDER = "File has been received, but is either corrupted or not present"
VICTIM_ACK = "ACK"

START_KEYLOG_MSG = "START"
CHECK_KEYLOG = "CHECK"
STATUS_TRUE = "TRUE"
STATUS_FALSE = "FALSE"
FILE_FOUND_MSG = "[+] The file {} exists in the current directory."
FILE_FOUND_MSG_TO_COMMANDER = "The file {} exists in the current directory."
FILE_NOT_FOUND_ERROR = "[+] ERROR: The file {file_name} does not exist in the current directory."
FILE_NOT_FOUND_TO_CMDR_ERROR = "ERROR: The file {file_name} does not exist in the current directory."
START_KEYLOGGER_PROMPT = "[+] Starting keylogger program..."
RECEIVE_FILE_NAME_PROMPT = "[+] Receiving command to check for file: {} if present..."
DO_CHECK_MSG = "[+] CHECKING FILE EXIST: Now checking if {} exists..."
